### ISSUE TITLE
Admin: Text in tables is not selectable

### ISSUE THREAD

**Issue by HeyJoel** [cofoundry-cms/cofoundry#380]
Text in tables is not selectable, can be fixed by overriding with this:

```css
td {
    user-select: text;
}
```

The `user-select` attribute seems to be set globally in the tags control css.
